name: ci

on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: test suite [otp=${{matrix.otp}}, elixir=${{matrix.elixir}}]
    strategy:
      matrix:
        otp: [24.x, 25.x, 26.x]
        elixir: [1.14.x]
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Cache Dependencies
        uses: actions/cache@v4.0.2
        with:
          path: |
            deps
            _build/dev
            _build/test
          key: elixir-cache-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            elixir-cache-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-
      - uses: erlef/setup-beam@v1.17.5
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Setup & Run Tests
        env:
          MIX_ENV: test
        run: |
          mix deps.get
          mix test --trace
      - name: Credo
        run: mix credo
      - name: Create PLTs
        run: mix dialyzer --plt
      - name: Dialyzer
        run: mix dialyzer
